language: python

cache: pip

python:
  - "3.9"

services:
  - postgresql
  - redis-server

install: "pip install -q -r requirements.txt"

jobs:
  include:
    - stage: lint
      script: flake8 ./src
    - stage: test
      env:
          - FLASK_ENV=testing
      before_script:
          - psql -c 'create database spz;' -U postgres
      script: pytest ./src
